 # 创建一个人工数据集，并存在csv文件里

In [2]:
import os #导入用于处理文件操作的OS模块

In [5]:
os.makedirs(os.path.join('.','data'))#创建文件夹

In [6]:
data = os.path.join('.','data','house_tiny.csv')

In [49]:
with open (data,'w') as f:
    f.write('num,alley\n')
    f.write('1,NaN\n')
    f.write('NaN,V\n')

## 读取的话可以使用pandas

In [13]:
import pandas as pd

In [50]:
data_r = pd.read_csv(data)
print(data_r)
data_r

   num alley
0  1.0   NaN
1  NaN     V

   num alley
0  1.0   NaN
1  NaN     V

## 处理缺失数据

### 插值

In [51]:
inputs,outputs = data_r.iloc[:,0:2],data_r.iloc[:,0:2]
inputs

   num alley
0  1.0   NaN
1  NaN     V

**没有数值时，显示的是NaN，固定格式，不能改动**

***name.fillna填充NaN，name.mean()取平均值 带上numeric_only = True只对数字进行处理，否则会报错***

In [52]:
inputs = inputs.fillna(inputs.mean(numeric_only = True))#fillna只能填充NaN
inputs

   num alley
0  1.0   NaN
1  1.0     V

pd.get_dummies()：是 Pandas 中用于独热编码的函数，会将类别型特征（如Alley列的 “Pave”“NaN”）转换为多个二进制列（0/1）

dummy_na=True：表示将缺失值（NaN）也视为一个独立的类别，单独生成一列标识。

In [53]:
inputs1 = pd.get_dummies(inputs,dummy_na = True)
inputs1

   num  alley_V  alley_nan
0  1.0    False       True
1  1.0     True      False

### 删除